import { AnimatePresence, AnimateSharedLayout, motion } from 'framer-motion'
import type { AppProps } from 'next/app'
import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'

import 'tailwindcss/tailwind.css'
import 'styles/globals.css'

import { AppStateProvider } from 'hooks'
import { ModalRouter } from 'components'

const PRESENCE_MOTION_PROPS = {
  initial: { opacity: 0 },
  animate: { opacity: 1 },
  exit: { opacity: 0 },
}

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter()

  return (
    <AppStateProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimateSharedLayout>
        <AnimatePresence exitBeforeEnter>
          <motion.main key={router.asPath} {...PRESENCE_MOTION_PROPS}>
            <Component {...pageProps} />
          </motion.main>
        </AnimatePresence>
      </AnimateSharedLayout>
      <ModalRouter />
    </AppStateProvider>
  )
}
export default MyApp
